export const trips = [
  {
    "tripName": "Cruising the Nile: A Voyage Through Ancient Egypt",
    "destination":"Cairo",
    "date": "27/5/2023",
    "duration": "7 days",
    "categories": ["River, ", "Short trips"],
    "rating": 4.7,
    "numOfParticipants": 10,
    "id":"14204",
    "price":167,
    "images":[require('./assets/trips-card-images/NileTrip/1.png'),
            require('./assets/trips-card-images/NileTrip/2.png'),
            require('./assets/trips-card-images/NileTrip/3.png'),
            require('./assets/trips-card-images/NileTrip/4.jpg'),

    ],
    "description":"Embark on a majestic journey down the Nile river, where you'll explore the awe-inspiring wonders of Ancient Egypt in comfort and style. Admire the timeless beauty of the Pyramids of Giza and the Great Sphinx, explore the mysterious tombs of the Valley of the Kings, and marvel at the towering temples of Luxor and Karnak. Along the way, you'll enjoy luxurious amenities on board a lavish cruise ship, from elegant dining to indulgent spa treatments, while taking in the stunning scenery of the Nile riverbanks. Immerse yourself in the rich history and culture of Egypt, as you discover the secrets of its ancient civilization and its enduring legacy that continues to inspire awe and wonder today."
  },
  {
    "tripName": "Giza Wonders: Discovering the Secrets of the Ancient World",
    "destination":"Giza",
    "date": "10/8/2023",
    "duration": "5 days",
    "categories": ["City, ", "Museum"],
    "rating": 4.2,
    "numOfParticipants": 8,
    "id":"114204",
    "price":60,
    "images":[require('./assets/trips-card-images/Giza/1.png'),
            require('./assets/trips-card-images/Giza/2.png'),
            require('./assets/trips-card-images/Giza/3.png'),
    ],
   
"description": "Explore the mysteries of the ancient world with a trip to Giza. Stand in awe of the Great Pyramids and Sphinx, marvel at the engineering and architecture of the ancient Egyptians, and learn about the secrets of this fascinating civilization. With knowledgeable guides and a comprehensive itinerary, this trip is perfect for history buffs and adventurers alike."


  },
  {
    "tripName": "Valley of the Kings: Unraveling the Mysteries of Luxor",
    "destination":"Luxor",
    "date": "15/9/2023",
    "duration": "10 days",
    "categories": ["City, ", "Shopping"],
    "rating": 4.9,
    "numOfParticipants": 12,
    "id":"1757574",
    "price":80,
    "images":[require('./assets/trips-card-images/Luxor/1.png'),
            require('./assets/trips-card-images/Luxor/2.png'),
            require('./assets/trips-card-images/Luxor/3.png'),
            require('./assets/trips-card-images/Luxor/4.png'),
    ],
    "description":"Step back in time and explore the ancient city of Luxor on the banks of the Nile. Visit the Karnak and Luxor Temples and marvel at their colossal pillars, obelisks and hieroglyphics. Cross to the west bank and witness the Valley of the Kings, where pharaohs were buried in elaborate tombs. Take a hot air balloon ride for a breathtaking view of the city and the Nile. Shop for souvenirs in the bustling bazaars, and relax in the evening while enjoying a traditional dinner on a Nile river cruise.",
  }, 
  {
    "tripName": "Nubian Oasis: Discovering the Beauty of Aswan",
    "destination":"Aswan",
    "date": "20/11/2023",
    "duration": "14 days",
    "categories": ["City, ", "Culture"],
    "rating": 4.6,
    "numOfParticipants": 6,
    "id":"175257",
    "price":120,
    "images":[require('./assets/trips-card-images/Aswan/1.png'),
            require('./assets/trips-card-images/Aswan/2.jpg'),
            require('./assets/trips-card-images/Aswan/3.jpg'),
    ],
    "description":"Embark on a journey to the serene city of Aswan, where ancient temples and colorful Nubian villages await. Explore the impressive Philae Temple, set on an island in the middle of the Nile River, and witness the grandeur of the High Dam. Cruise down the river to visit the magnificent Abu Simbel temples, built by the great pharaoh Ramses II, and marvel at the intricate carvings and engineering feats. Shop in the bustling souks for traditional handicrafts and soak up the warm hospitality of the friendly locals."
  },
  {
    "tripName": "Paradise Found: Exploring the Wonders of Sharm El Sheikh",
    "destination":"Sharm El-Sheikh",
    "date": "5/1/2024",
    "duration": "12 days",
    "categories": ["Beach, ", "Nature"],
    "rating": 4.8,
    "numOfParticipants": 8,
    "id":"1577742",
    "price":400,
    "images":[require('./assets/trips-card-images/Sharm/1.png'),
            require('./assets/trips-card-images/Sharm/2.png'),
            require('./assets/trips-card-images/Sharm/3.png'),
    ],
    "description":"Experience the beauty of the Red Sea with a trip to Sharm El Sheikh. Soak up the sun on pristine beaches, swim in crystal-clear waters, and explore the vibrant coral reefs on a snorkeling or diving excursion. Take a camel ride in the desert or enjoy a quad bike adventure. With luxurious resorts and top-notch amenities, Sharm El Sheikh is the perfect destination for a relaxing and adventurous getaway."
  },
  {
    "tripName": "Dahab Delights: Exploring the Beauty of Sinai's Coastal Gem",
    "destination":"Sinai",
    "date": "1/3/2024",
    "duration": "8 days",
    "categories": ["Beach, ", "City"],
    "rating": 4.5,
    "numOfParticipants": 10,
    "id":"15775",
    "price":200,
    "images":[require('./assets/trips-card-images/Dahab/1.png'),
            require('./assets/trips-card-images/Dahab/2.png'),
            require('./assets/trips-card-images/Dahab/3.png'),
    ],
    "description":"Explore the stunning seaside town of Dahab, known for its laid-back vibe and world-class diving sites. Dive into crystal-clear waters to discover vibrant marine life and unique underwater landscapes. Relax on the soft sandy beaches or indulge in water sports such as kiteboarding and windsurfing. Take a stroll down the vibrant boardwalk and immerse yourself in the colorful local culture, or venture into the nearby Sinai desert for a thrilling excursion."
  },
  {
    "tripName": "From Desert to Sea: A Journey Through the Wonders of Hurghada",
    "destination":"Hurghada",
    "date": "15/5/2024",
    "duration": "10 days",
    "categories": ["Beach, ", "Nature"],
    "rating": 4.7,
    "numOfParticipants": 6,
    "id":"752721",
    "price":190,
    "images":[require('./assets/trips-card-images/Harghada/1.png'),
            require('./assets/trips-card-images/Harghada/2.png'),
    ],
    "description":"Indulge in a seaside escape at Hurghada, with crystal clear waters and coral reefs teeming with vibrant marine life, perfect for snorkeling and diving enthusiasts. Relax on pristine beaches, explore lively bazaars, and enjoy various water sports activities. Take a day trip to nearby islands or immerse in the local culture with a visit to traditional villages and historic sites."
  },
  
  {
    "tripName": "A Red Sea Paradise: Exploring the Wonders of Taba",
    "destination":"Taba",
    "date": "10/9/2024",
    "duration": "14 days",
    "categories": ["Nature, ", "Safari"],
    "rating": 4.9,
    "numOfParticipants": 4,
    "id":"12121",
    "price":198,
    "images":[require('./assets/trips-card-images/Taba/1.png'),
            require('./assets/trips-card-images/Taba/2.png'),
            require('./assets/trips-card-images/Taba/3.png'),
    ],
    "description":"Embark on a journey to the serene Taba and witness the breathtaking beauty of the Red Sea, explore the colorful coral reefs, and indulge in a variety of water activities, including snorkeling and diving. Admire the majestic mountains of Sinai, relax in the luxurious resorts, and enjoy the stunning panoramic views of Egypt, Israel, Jordan, and Saudi Arabia. Experience the unique blend of nature, culture, and adventure in Taba."
  },
  {
    "tripName": "Red Sea Magic: A Scuba Diving Adventure of a Lifetime",
    "destination":"The Red Sea",
    "date": "1/12/2024",
    "duration": "12 days",
    "categories": ["Beach, ", "Nature"],
    "rating": 4.6,
    "numOfParticipants": 6,
    "id":"1dsaw",
    "price":220,
    "images":[require('./assets/trips-card-images/RedSea/1.png'),
            require('./assets/trips-card-images/RedSea/2.png'),
            require('./assets/trips-card-images/RedSea/3.png'),
    ],
    "description":"Embark on a scuba diving adventure in the stunning Red Sea, renowned for its crystal-clear waters and vibrant marine life. Explore vibrant coral reefs, shipwrecks, and underwater landscapes, while encountering a variety of colorful fish and marine creatures. Relax in luxurious seaside resorts and enjoy activities such as snorkeling, windsurfing, and kayaking. Discover the stunning natural beauty of the Red Sea and create unforgettable memories."
  }
]
